# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: 'en-us'
  contentDir: 'content/en'
  title: 'UdeC Plasma Group'
  copyright: '&copy; {year} - Plasma Physics Group, Universidad de Concepción'
  params:
    description: 'Site description'

es:
  languageCode: 'es-cl'
  contentDir: 'content/es'
  title: 'Grupo de Plasmas UdeC'
  copyright: '&copy; {year} - Grupo de Física de Plasmas, Universidad de Concepción'
  params:
    description: 'Descripción del sitio'
